definitions:
  httperrors.Details:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  httperrors.Response:
    properties:
      error:
        $ref: '#/definitions/httperrors.Details'
      validation:
        items:
          type: string
        type: array
    type: object
  models.Task:
    properties:
      createdAt:
        type: string
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      httpStatusCode:
        type: integer
      id:
        type: string
      length:
        type: integer
      status:
        type: string
      updatedAt:
        type: string
    type: object
  models.TaskRequest:
    properties:
      body:
        type: object
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  models.TaskResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Create task
      parameters:
      - description: Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.Response'
      tags:
      - taskCreate
  /task/{id}:
    get:
      consumes:
      - application/json
      description: Get task by id
      parameters:
      - description: Task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.Response'
      tags:
      - taskById
swagger: "2.0"
